# Generated by Django 5.2.7 on 2026-09-29 06:15

import commerce.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('stripe_price_id', models.CharField(blank=True, max_length=120)),
                ('external_checkout_url', models.URLField(blank=True)),
                ('currency', models.CharField(default='MYR', max_length=3)),
                ('destination_type', models.CharField(choices=[('form', 'Form'), ('booking', 'Booking')], default='form', max_length=16)),
                ('destination_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('destination_url', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(default='created', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.actionmapping')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.landingpage')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.customer')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('amount_total', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='myr', max_length=3)),
                ('status', models.CharField(default='paid', max_length=32)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commerce.checkoutattempt')),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=commerce.models.journey_token, max_length=80, unique=True)),
                ('destination_type', models.CharField(choices=[('booking', 'Booking'), ('form', 'Form')], default='form', max_length=16)),
                ('destination_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('destination_url', models.URLField(blank=True)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_source', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='commerce.customer')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journey', to='commerce.payment')),
            ],
        ),
    ]
