# Generated by Django 5.2.7 on 2026-09-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_checkoutattempt_page_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('zh', '中文')], default='en', max_length=8),
        ),
    ]
