# Generated by Django 5.2.7 on 2026-09-29 06:14

import django.core.validators
import django.db.models.deletion
import pages.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9-]*$', 'Use lowercase letters, numbers and hyphens.')])),
                ('source_type', models.CharField(choices=[('builder', 'Section builder'), ('upload', 'Code upload')], default='builder', max_length=12)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=253, unique=True)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('verification_token', models.CharField(default=pages.models.domain_token, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='pages.landingpage')),
            ],
        ),
        migrations.CreateModel(
            name='ActionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80)),
                ('action_type', models.CharField(choices=[('checkout', 'checkout'), ('booking', 'booking'), ('form', 'form'), ('external-checkout', 'external-checkout')], max_length=24)),
                ('label', models.CharField(max_length=120)),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('target_url', models.URLField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='pages.landingpage')),
            ],
        ),
        migrations.CreateModel(
            name='ActionClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.actionmapping')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='pages.landingpage')),
            ],
        ),
        migrations.CreateModel(
            name='PageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('blocks', models.JSONField(blank=True, default=list)),
                ('artifact_path', models.CharField(blank=True, max_length=500)),
                ('detected_actions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pages.landingpage')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='landingpage',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for', to='pages.pageversion'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_for', to='pages.pageversion'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('referrer', models.URLField(blank=True, max_length=1000)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='pages.landingpage')),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.pageversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='actionmapping',
            constraint=models.UniqueConstraint(fields=('page', 'key'), name='unique_page_action'),
        ),
        migrations.AddConstraint(
            model_name='pageversion',
            constraint=models.UniqueConstraint(fields=('page', 'number'), name='unique_page_version'),
        ),
    ]
