# Generated by Django 5.2.7 on 2026-09-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(default='queued', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('payment_confirmation', 'Payment Confirmation'), ('action_request', 'Action Request'), ('reminder', 'Reminder'), ('booking_confirmation', 'Booking Confirmation'), ('booking_cancelled', 'Booking Cancelled'), ('booking_rescheduled', 'Booking Rescheduled')], max_length=40)),
                ('subject_en', models.CharField(max_length=250)),
                ('subject_zh', models.CharField(blank=True, max_length=250)),
                ('body_en', models.TextField()),
                ('body_zh', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReminderStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('delay_hours', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['delay_hours'],
            },
        ),
    ]
