# Generated by Django 5.2.7 on 2026-09-29 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automations', '0001_initial'),
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildelivery',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='commerce.journey'),
        ),
        migrations.AddField(
            model_name='emaildelivery',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='automations.emailtemplate'),
        ),
        migrations.AddField(
            model_name='reminderstep',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='automations.emailtemplate'),
        ),
        migrations.AddField(
            model_name='emaildelivery',
            name='reminder_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automations.reminderstep'),
        ),
        migrations.AddConstraint(
            model_name='emaildelivery',
            constraint=models.UniqueConstraint(fields=('journey', 'template', 'reminder_step'), name='unique_journey_email_step'),
        ),
    ]
