# Generated by Django 5.2.7 on 2026-09-29 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_initial'),
        ('bookings', '0002_initial'),
        ('commerce', '0003_customer_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildelivery',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='emaildelivery',
            name='journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='commerce.journey'),
        ),
    ]
