# Generated by Django 5.2.7 on 2026-09-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0003_emaildelivery_booking_alter_emaildelivery_journey'),
        ('bookings', '0002_initial'),
        ('commerce', '0003_customer_preferred_language'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='emaildelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', True), ('journey__isnull', False)), models.Q(('booking__isnull', False), ('journey__isnull', True)), _connector='OR'), name='email_delivery_exactly_one_subject'),
        ),
    ]
