# Generated by Django 5.2.7 on 2026-09-29 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCompletionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=160, unique=True)),
                ('submission_id', models.CharField(max_length=160)),
                ('completed_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_events', to='commerce.journey')),
            ],
        ),
    ]
