# Generated by Django 5.2.7 on 2026-09-29 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('commerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='commerce.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='commerce.journey'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.bookingtype'),
        ),
        migrations.AddField(
            model_name='calendarconnection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='host',
            name='calendar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='bookings.calendarconnection'),
        ),
        migrations.AddField(
            model_name='bookingtype',
            name='hosts',
            field=models.ManyToManyField(related_name='booking_types', to='bookings.host'),
        ),
        migrations.AddField(
            model_name='booking',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.host'),
        ),
        migrations.AddField(
            model_name='slothold',
            name='booking_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.bookingtype'),
        ),
        migrations.AddField(
            model_name='slothold',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.host'),
        ),
        migrations.AddField(
            model_name='timeoff',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to='bookings.host'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='bookings.host'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('host', 'starts_at', 'status'), name='unique_host_booking_slot'),
        ),
        migrations.AddConstraint(
            model_name='workinghours',
            constraint=models.UniqueConstraint(fields=('host', 'weekday', 'start_time'), name='unique_host_hours'),
        ),
    ]
